version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      k8s-io:
        patterns:
        - "k8s.io/*"
        - "sigs.k8s.io/*"
      ginkgo-and-gomega:
        patterns:
        - github.com/onsi/ginkgo/v2
        - github.com/onsi/gomega
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
