---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - desec.owly.dedyn.io
  resources:
  - desecdns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - desec.owly.dedyn.io
  resources:
  - desecdns/finalizers
  verbs:
  - update
- apiGroups:
  - desec.owly.dedyn.io
  resources:
  - desecdns/status
  verbs:
  - get
  - patch
  - update
# Ingress
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - get
