name: Build

on:
  push:
    tags-ignore:
    - '**'
    branches:
      - '**'

jobs:
  buildx:
    name: Build

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Setup Buildx
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64,linux/arm64

    # Build
    - name: Build
      uses: docker/build-push-action@v4
      with:
        platforms: linux/amd64
