name: Build and Push

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  buildx:
    name: Build and push

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Setup Buildx
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/amd64,linux/arm64

    # Login
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Extract metadata
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}

    # Build
    - name: Build
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64

    # Load
    - name: Load AMD64
      uses: docker/build-push-action@v6
      with:
        load: true
        platforms: linux/amd64
        tags: dummy-tag:amd64
    - name: Load ARM64
      uses: docker/build-push-action@v6
      with:
        load: true
        platforms: linux/arm64
        tags: dummy-tag:arm64

    # Push
    - name: Push both
      uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
